### ISSUE TITLE
Clarify readme

### ISSUE THREAD

**Issue by hfossli** [ellefsen/wordpress-heroku-php#2]
The readme states

> Add this below Heroku Toolbelt setting to swap the PHP you use on the command line.
> 
> ```
> export PATH="$(brew --prefix homebrew/php/php55)/bin:$PATH"
> ```

I don't quite understand what I'm supposed to do. Can you clarify a little?

**Comment by ellefsen** [comment]
Of course. You should add the path of your freshly installed and compiled php installation to the shell startup script. On Mac this would typically be `.bashrc` or `.profile` in your home directory. Or if you are using something like zsh then it would be `.zshrc` .

If you run `$PATH` in Terminal you will see all the paths your shell will look for scripts, so that when you run `php -v` it will try to execute php from one of those paths if it is present. If you don't add it you will only see the pre-installed php version that Mac OS provides. 

If you are running El Capitan you can skip this step as PHP 5.5 is the default version.

Hope this helps.

**Comment by hfossli** [comment]
Takk! :)
